### ISSUE TITLE
Add LICENSE file to project

### ISSUE THREAD

**Issue by FlaggAC** [aquafir/ACE.BaseMod#3]
A few of the files like [this one](https://github.com/aquafir/ACE.BaseMod/blob/f54202ae2f6c7007d080f0343aefccea4bc7d816/Samples/AutoLoot/Lib/VTClassic/FileVersioning.cs#L15) have a license header. Could we have a `LICENSE` file at the repository root to indicate that permission is granted to use/modify/distribute the code under an appropriate license?

Here is some information about what "No License" means:
https://choosealicense.com/no-permission/

**Comment by aquafir** [comment]
Added AGPL license
